webPortal/account/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.loginHandler,name='login'),
    path('forgot/', views.forgot,name='forgot'),
    path('logout/', views.logoutHandler,name='logout'),
]

webPortal/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index,name='index'),
    path('papers/',views.papers,name='papers'),
    path('patents/',views.patents,name='patents'),

]

webPortal/webPortal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',include('dashboard.urls')),
    path('account/',include('account.urls')),
    path('', lambda a : redirect('/account/login')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webPortal/account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    faculty_name = models.CharField(max_length=70)
    designation = models.CharField(max_length=200)
    employee_id = models.PositiveBigIntegerField()
    email = models.EmailField()
    contact_number = models.PositiveBigIntegerField()
    date_of_joining = models.DateField(auto_created=True)


    def __str__(self):
        return self.faculty_name

webPortal/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Paper(models.Model):

    author = models.OneToOneField(User,on_delete=models.CASCADE)
    paper_title = models.CharField(max_length=400)
    paper_published_date = models.DateField()
    paper_publisher = models.CharField(max_length=400)
    paper_proof = models.FileField(upload_to='papers-proof')

    def __str__(self):
        return self.paper_title

webPortal/account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.http import HttpResponse
from django.contrib.auth import get_user_model , logout
from django.contrib import messages

# Create your views here.


def loginHandler(request) -> HttpResponse:

    if request.method == "POST":
        sign_in_email = request.POST.get("email", None)
        sign_in_password = request.POST.get("password", None)

        if sign_in_email == None or sign_in_password == None:
            messages.add_message(request, messages.ERROR, "Unauthorized request")
            return HttpResponse("<h1>Something went wrong</h1>")

        userModel = get_user_model()

        try:
            user = userModel.objects.get(email=sign_in_email)
        except userModel.DoesNotExist:
            messages.add_message(
                request, messages.WARNING, "Incorrect email or password"
            )
            return render(request, "account/login.html")
        else:
            if user.check_password(sign_in_password) and user.is_active:
                auth.login(request, user)
                return redirect("/dashboard")

            messages.add_message(
                request, messages.WARNING, "Incorrect email or password"
            )
            return render(request, "account/login.html")
    else:
        return render(request, "account/login.html")


def forgot(request) -> HttpResponse:
    return render(request, "account/forgot.html")

def logoutHandler(request)->HttpResponse:
    logout(request)
    return redirect("/account/login")

webPortal/dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from account.models import Profile
from dashboard.models import Paper

# Create your views here.


def index(request) -> HttpResponse:

    if request.user.is_authenticated and request.user.is_active:
        get_profile = Profile()
        try:
            get_profile = Profile.objects.get(email=request.user.email)
        except get_profile.DoesNotExist:
            return render(request, "dashboard/index.html", {"profile": False})
        else:
            return render(request, "dashboard/index.html", {"profile": get_profile})
    else:
        return redirect("/account/login")


def papers(request) -> HttpResponse:
    if request.user.is_authenticated and request.user.is_active:
        get_profile = Profile()
        get_papers = Paper()
        try:
            get_profile = Profile.objects.get(email=request.user.email)
            get_papers = Paper.objects.filter(author=request.user)
        except get_profile.DoesNotExist or get_papers.DoesNotExist:
            return render(
                request, "dashboard/papers.html", {"profile": False, "papers": False}
            )
        else:
            return render(
                request,
                "dashboard/papers.html",
                {"profile": get_profile, "papers": get_papers},
            )
    else:
        return redirect("/account/login")


def patents(request) -> HttpResponse:
    if request.user.is_authenticated and request.user.is_active:
        return render(request, "dashboard/patents.html")
    else:
        return redirect("/account/login")

webPortal/templates/dashboard/Papers.html
{% extends 'dashboard/base.html' %}
{% block current %}Papers{% endblock current %}

{% block body %}
{% if profile %}
  <div class="container-fluid">
    <div class="main-body">
      <div class="row justify-content-around">
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                  width="150">
                <div class="mt-3">
                  <h4>{{profile.faculty_name}}</h4>
                </div>
              </div>
            </div>
          </div>
          <div class="card mt-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h6 class="mb-0">Faculty Name</h6>
                <span class="text-secondary">{{profile.faculty_name}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h6 class="mb-0">Designation</h6>
                <span class="text-secondary">{{profile.designation}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h6 class="mb-0">Email</h6>
                <span class="text-secondary">{{profile.email}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h6 class="mb-0">Date of Joining</h6>
                <span class="text-secondary">{{profile.date_of_joining}}</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                <h6 class="mb-0">Facebook</h6>
                <span class="text-secondary">bootdey</span>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-8">
          <center>
            <h3 style="color:#17a2b8 ;">All Papers</h3>
          </center>
          <div class="table-responsive" style="border:1px solid rgba(0,0,0,.125);border-radius:0.25em;">
            <table class="table table-bordered table-hover">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Paper name</th>
                  <th scope="col">Published at</th>
                  <th scope="col">Publisher</th>
                  <th scope="col">Proof</th>
                </tr>
              </thead>
              <tbody>
                {% for paper in papers %}
                  <tr>
                    <td class="table-row">{{paper.paper_title}}</td>
                    <td>{{paper.paper_published_date}}</td>
                    <td class="table-row">{{paper.paper_publisher}}</td>
                    <td><a href="{{paper.paper_proof.url}}" target="_blank">View Proof</a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% else %}
<h1>Profile Not found</h1>
{% endif %}
<style>
  .table {
    table-layout: fixed;
    margin-bottom: 0px;
  }
</style>
{% endblock body %}

webPortal/templates/dashboard/Patents.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="papers.css" rel="stylesheet">
</head>
<body>
  <nav>
    <div class="menu">
    <ul>
        <li class="awards"><a href='#'>Awards</a></li>
        <li><a href='#'>Papers/Patents</a>
          <div class="sub1">
          <ul>
            <li><a href='Papers.html'>Papers</a></li>
            <li><a href='Patents.html'>Patents</a></li>
          </ul>
          </div>
        </li>
        <li><a href='#'>Funds Received</a></li>
        <li><a href='#'>Other Noteworthy Activity</a></li>
        <button id="bt" type="submit"><a style="margin: 15px;" href="Loginpage.html">Logout</a></button>
    </ul>
  </div>
   </nav>
   <div class="sidebar">
   <div class="row">
  <div class="card-body">
   <img src="image.jpeg" class="rounded circle" width=150>
  </div> 
<!--</div> 
  <div class="card-body">
    <div class="row">
    
      <div class="col-md-3">
          <h5>Faculty name</h5>
      </div>
      <div class="col-md-text-secondary">
          xyz
      </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <h5>Designation</h5>
        </div>
        <div class="col-md-text-secondary">
            Proffessor
        </div>
      </div>
    
    <div class="row">
        <div class="col-md-3">
            <h5>Employee id</h5>
        </div>
        <div class="col-md-text-secondary">
            empid1234
        </div>
      </div>
    
    <div class="row">
        <div class="col-md-3">
            <h5>Mail</h5>
        </div>
        <div class="col-md-text-secondary">
           abc@gmail.com
        </div>
      </div>
    <div class="row">
        <div class="col-md-3">
            <h5>Contact No</h5>
        </div>
        <div class="col-md-text-secondary">
            1234567890
        </div>
      </div>
    <div class="row">
        <div class="col-md-3">
            <h5>Date of Joining</h5>
        </div>
        <div class="col-md-text-secondary">
            01/01/2000
        </div>
      </div>
</div>
</div>-->

  
<!-- 
</body>
</html>  -->
{% extends 'dashboard/base.html' %}
{% block current %}Patents{% endblock current %}
{% block body %}
<div>
  <table>
    <tr>
      <td><strong>Patent Name</strong></td>
      <td><strong>Published in</strong></td>
      <td><strong>Publisher</strong></td>
      <td><strong>Proof</strong></td>
    </tr>
    <tr>
      <td>Donuts</td>
      <td>19/03/2022</td>
      <td>NDTV</td>
      <td>Kamal Hassan</td>
    </tr>
  </table>
</div>
<div class="f1">
  <form action="#" class="f2">
    <input type="text" name="Patent" style="margin-top: 100px;" id="p" placeholder="Patent" accept="text/*">
    <h1></h1>
    <input type="text" name="Published in" id="pin" placeholder="Published in" accept="text/*">
    <h1></h1>
    <input type="text" name="Publisher" id="pub" placeholder="Publisher" accept="text/*">
    <h1></h1>
    <div style="margin: auto; display:block;">Submit Proof</div>
    <input type="file" id="proof" name="proof" style="text-align:center;" id="pr" accept="file/*">
    <h1></h1>
    <input type="submit" id="submit">
  </form>
</div>
{% endblock body %}

webPortal/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard</title>
  <link href="{% static 'css/new.css' %}" rel="stylesheet">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <nav class="nav" style="padding:40px ;">
    <div class="select">
      <a class="link color-main  dropdown-toggle" id="navigation_2_dropdown_1">{% block current %} {% endblock current%}</a>
      <div class="dropdown-menu">
        <div><a href="{% url 'dashboard:papers' %}">Papers</a></div>
        <div><a href="{% url 'dashboard:patents' %}">Patents</a></div>
        <div><a>Awards</a></div>
        <div><a>Notewothy</a></div>
      </div>
    </div>
    <div class="logo">
      <img src="{% static 'images/logo.svg' %}" width="200px" />
    </div>
    <div class="row">
      <div class="col">
        <!-- <div class="login btn btn-primary">
          <button>{{request.user.email}}</button>
        </div> -->
      </div>
      <div class="col">
        <div class="login btn btn-danger">
          <button><a href="{% url 'account:logout' %}" role="button"
              style="text-decoration:none;color:white">Logout</a></button>
        </div>

      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock body %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="{% static 'js/navbar.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>

</body>

</html>

webPortal/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block current %}Home{% endblock current %}

{% block body %}

{% if profile %}
<div class="container-fluid">
  <div class="main-body">
    <div class="row justify-content-around">
      <div class="col-sm-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                width="150">
              <div class="mt-3">
                <h4>{{profile.faculty_name}}</h4>

              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-globe mr-2 icon-inline">
                  <circle cx="12" cy="12" r="10"></circle>
                  <line x1="2" y1="12" x2="22" y2="12"></line>
                  <path
                    d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z">
                  </path>
                </svg>Website</h6>
              <span class="text-secondary">https://bootdey.com</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-github mr-2 icon-inline">
                  <path
                    d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22">
                  </path>
                </svg>Github</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-twitter mr-2 icon-inline text-info">
                  <path
                    d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z">
                  </path>
                </svg>Twitter</h6>
              <span class="text-secondary">@bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-instagram mr-2 icon-inline text-danger">
                  <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                </svg>Instagram</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                  fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-facebook mr-2 icon-inline text-primary">
                  <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                </svg>Facebook</h6>
              <span class="text-secondary">bootdey</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Faculty Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.faculty_name}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Designation</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.designation}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Employee id</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.employee_id}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.email}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Contact Number</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.contact_number}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Date of Joining</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{profile.date_of_joining}}
              </div>
            </div>
          </div>
        </div>

        <div class="row gutters-sm">
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i
                    class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                <small>Web Design</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Website Markup</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>One Page</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Mobile Template</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Backend API</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-6 mb-3">
            <div class="card h-100">
              <div class="card-body">
                <h6 class="d-flex align-items-center mb-3"><i
                    class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                <small>Web Design</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Website Markup</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>One Page</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Mobile Template</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <small>Backend API</small>
                <div class="progress mb-3" style="height: 5px">
                  <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66"
                    aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>



      </div>
    </div>

  </div>
</div>
{% else %}
<h1>Profile Not Found</h1>
{% endif %}
{% endblock body %}